---
- name: "Configure NHC for OCP Virtualization"
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars.yaml
  tasks:
    - name: "Create Namespace {{ node_health_check_namespace }}"
      kubernetes.core.k8s:
        state: present
        template: node-health-check-namespace.yml.j2

    - name: "Create OperatorGroup {{ workload_availability_operator_group }}"
      kubernetes.core.k8s:
        state: present
        template: workload-availability-operator-group.yml.j2

    - name: "Create Subscription node-health-check-operator"
      kubernetes.core.k8s:
        state: present
        template: node-health-check-subscription.yml.j2

          #    - name: "Create OperatorGroup self-node-remediation-operator"
          #      kubernetes.core.k8s:
          #        state: present
          #        template: snr-og.yml.j2
          #
    - name: "Create Subscription self-node-remediation-operator"
      kubernetes.core.k8s:
        state: present
        template: snr-subscription.yml.j2

